### ISSUE TITLE
roach asf

### ISSUE THREAD

**Issue by Kolonyaa** [YABOIpy/YABOIpy#1]
ayo wsp get sum money p0oron😂💸💰☝️☝️can't see yo stacks, pack soon? 🤣🤣

**Comment by Kolonyaa** [comment]
![yande re 822268 bikini dikko erect_nipples eyepatch fischl garter genshin_impact swimsuits wet](https://user-images.githubusercontent.com/50084113/181921072-80869b63-21ea-46e5-be40-258c565a4616.jpg)

get yoself sum real bitches see above 😯👆

**Comment by Kolonyaa** [comment]
![drawn_by_seele0907__97d8fdee6196e65197c57fa28966788e-1](https://user-images.githubusercontent.com/50084113/181921136-51b022e1-b005-49c7-8cf5-bef3a1f9b18b.jpg)

more bitches to look at while you jealous 😉

**Comment by Kolonyaa** [comment]
![houshou_marine_hololive_drawn_by_tofuubear__a62be051b96453e16c55bbd01ccf154c](https://user-images.githubusercontent.com/50084113/181921192-60909013-c65f-48ac-8361-2c445c109775.jpg)

off yourself

**Comment by Kolonyaa** [comment]
![houshou_marine_hololive_drawn_by_oshiruko_oshiruco_212048__7f976189f61714fde3712461485a3bea](https://user-images.githubusercontent.com/50084113/181922175-976d4f06-6dfd-41e2-9ccf-bb38433cc07f.jpg)

yk why I created an issue? cuz you got a shitton of issues on God here's one of em🤣🤣☝️☝️

**Comment by YABOIpy** [comment]
I see a man of god

**Comment by YABOIpy** [comment]
Bet we finna pack my Stunna boy 😂😂☝️☝️🤞🤑🤑

**Comment by mytix999** [comment]
update discord link

**Comment by Kolonyaa** [comment]
> update discord link

u a pussy Mike Tyson would beat the shit out of you🤣🤣🤣nigha u so weak u gotta skid ur life to succeed u ain't got no money u can't pull no bitches asking for an invite I get yo acc pwned rq see ya skiddyboy👆👆🤣🤣

**Comment by YABOIpy** [comment]
> update discord link

https://discord.gg/ANRcpx95

**Comment by YABOIpy** [comment]
> > update discord link
> 
> u a pussy Mike Tyson would beat the shit out of you🤣🤣🤣nigha u so weak u gotta skid ur life to succeed u ain't got no money u can't pull no bitches asking for an invite I get yo acc pwned rq see ya skiddyboy👆👆🤣🤣

That boy a fake cuh u be all on me cuh he crazy loc u not a real stunna !!
